# HARDCODED CONSTANTS
# DO NOT CHANGE

PORT = 22010
BUFFER_SIZE = 2 ** 16

# API_BASE_URL = 'http://localhost:8000/api'
API_BASE_URL = 'http://www.quantnode.com/api'
API_VERSION = 'v1'
API_URL = '%s/%s/' % (API_BASE_URL, API_VERSION)

STOP_FLAG = 'STOP'
CONTINUE_FLAG = 'CONTINUE'
END_FLAG = 'END'
